import pandas as pd
df = pd.read_csv("titanic.csv")
print("First 5 Rows of the Dataset:")
print(df.head())
import pandas as pd
df = pd.read_csv("titanic.csv")
print("First 5 Rows:")
print(df.head())
print("\nDataset Information:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
import pandas as pd
df = pd.read_csv("titanic.csv")
print("First 5 Rows:")
print(df.head())
print("\nDataset Information:")
print(df.info())
print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop(columns=["Cabin"])
df = df.drop_duplicates()
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())
df.to_csv("cleaned_titanic.csv", index=False)
print("\n✅ Data Cleaning Completed Successfully!")
